name: buildlinux

on:
  push:
    tags:
      - '*'
  pull_request: # Ajout de la v√©rification des PR
    branches:
      - '*'

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Install Dependencies on Ubuntu lts 20
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libx11-dev libxrandr-dev libxrender-dev libxfixes-dev libxcursor-dev libxinerama-dev mesa-common-dev libudev-dev libopenal-dev libvorbis-dev libflac-dev libfreetype6-dev

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build with CMake
        run: cmake --build build